// Code generated by cocoon. DO NOT EDIT.
package wasm

import "testing"

func TestGeneratedBulkMemoryBounds(t *testing.T) {
	t.Parallel()
	memory := make([]byte, 1, 8)
	tests := []func(){
		func() { memory_init(memory, "abc", uint32(1), uint32(0), uint32(1)) }, func() { memory_init(memory, "abc", uint32(0), uint32(4), uint32(0)) },
		func() { memory_copy(memory, uint32(1), uint32(0), uint32(1)) }, func() { memory_copy(memory, uint32(0), uint32(2), uint32(0)) },
		func() { memory_fill(memory, uint32(1), int32(1), uint32(1)) }, func() { memory_fill(memory, uint32(2), int32(1), uint32(0)) },
		func() { memory_zero(memory, uint32(1), uint32(1)) }, func() { memory_zero(memory, uint32(2), uint32(0)) },
	}
	for _, test := range tests {
		func() {
			defer func() {
				if recover() == nil {
					t.Error("operation crossed logical memory length")
				}
			}()
			test()
		}()
	}
}
