// Code generated by cocoon. DO NOT EDIT.
package dd

import (
	"context"
	"encoding/binary"
	"github.com/darccio/cocoon/rt"
	"log/slog"
	"math"
	"runtime"
	"sync"
	"unicode/utf8"
)

const schemaHash uint64 = 10905104844739090753
const maximumMemory uint64 = 268435456

type Options struct {
	Logger              *slog.Logger
	MaxInput, MaxOutput uint64
	Instances           int
}
type guest struct {
	module   *module
	instance *rt.Instance
}

func (g *guest) close() { g.instance.Close(); g.module = nil }

type Library struct {
	pool    *rt.Pool[guest]
	home    *guest
	options Options
	homeMu  sync.Mutex
	life    rt.Lifecycle
}

func Open(options Options) (*Library, error) {
	if options.MaxInput == 0 {
		options.MaxInput = 67108864
	}
	if options.MaxOutput == 0 {
		options.MaxOutput = 67108864
	}
	if options.MaxInput > 67108864 || options.MaxOutput > 67108864 || options.Instances < 0 {
		return nil, rt.ErrTooLarge
	}
	if options.Instances == 0 {
		options.Instances = runtime.GOMAXPROCS(0)
	}
	l := &Library{options: options}
	pool, err := rt.NewPool(options.Instances, l.newGuest, func(g *guest) bool { return g.instance.Recycle(65536, maximumMemory) }, func(g *guest) { g.close() })
	if err != nil {
		return nil, err
	}
	l.pool = pool
	return l, nil
}
func (l *Library) newGuest() (_guest *guest, _err error) {
	defer func() {
		if value := recover(); value != nil {
			_err = rt.Classify("construct", value, "")
		}
	}()
	raw, host := newModule(l.options)
	instance, err := rt.NewInstance(raw, schemaHash, rt.Limits{MaxInput: l.options.MaxInput, MaxOutput: l.options.MaxOutput, MaxMemory: maximumMemory}, host)
	if err != nil {
		return nil, err
	}
	return &guest{module: raw, instance: instance}, nil
}
func (l *Library) admission(ctx context.Context) error {
	if l == nil {
		return rt.ErrClosed
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	return l.life.Enter()
}
func (l *Library) getHome() (*guest, error) {
	l.homeMu.Lock()
	defer l.homeMu.Unlock()
	if l.home != nil && !l.home.instance.Healthy() {
		l.home.close()
		l.home = nil
	}
	if l.home == nil {
		home, err := l.newGuest()
		if err != nil {
			return nil, err
		}
		l.home = home
	}
	return l.home, nil
}
func (l *Library) Close() error {
	if l == nil {
		return nil
	}
	return l.life.Close(func() error {
		err := l.pool.Close()
		l.homeMu.Lock()
		defer l.homeMu.Unlock()
		if l.home != nil {
			l.home.close()
			l.home = nil
		}
		return err
	})
}
func boolParam(value bool) int32 {
	if value {
		return 1
	}
	return 0
}
func sizeString(value string, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 1)
}
func sizeBytes(value []byte, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 1)
}
func encodeString(value string, limit uint64) ([]byte, error) {
	if _, err := sizeString(value, limit); err != nil {
		return nil, err
	}
	if !utf8.ValidString(value) {
		return nil, &rt.AppError{Status: rt.ErrArg, Op: "encode", Message: "invalid UTF-8"}
	}
	return []byte(value), nil
}
func encodeBytes(value []byte, limit uint64) ([]byte, error) {
	if _, err := sizeBytes(value, limit); err != nil {
		return nil, err
	}
	return value, nil
}
func decodeString(data []byte, limit uint64) (string, error) {
	if uint64(len(data)) > limit {
		return "", rt.ErrTooLarge
	}
	if !utf8.Valid(data) {
		return "", rt.ErrProtocol
	}
	return string(data), nil
}
func decodeBytes(data []byte, limit uint64) ([]byte, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	return append([]byte(nil), data...), nil
}
func sizeBool(_ bool, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 1) }
func encodeBool(value bool, limit uint64) ([]byte, error) {
	if limit < 1 {
		return nil, rt.ErrTooLarge
	}
	return []byte{byte(boolParam(value))}, nil
}
func decodeBool(data []byte, _ uint64) (bool, error) {
	if len(data) != 1 || data[0] > 1 {
		return false, rt.ErrProtocol
	}
	return data[0] == 1, nil
}
func sizeI32(_ int32, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 4) }
func encodeI32(value int32, limit uint64) ([]byte, error) {
	if limit < 4 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint32(nil, uint32(value)), nil
}
func decodeI32(data []byte, _ uint64) (int32, error) {
	if len(data) != 4 {
		return 0, rt.ErrProtocol
	}
	return int32(binary.LittleEndian.Uint32(data)), nil
}
func sizeSliceI32(value []int32, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 4)
}
func encodeSliceI32(values []int32, limit uint64) ([]byte, error) {
	size, err := sizeSliceI32(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint32(data, uint32(value))
	}
	return data, nil
}
func decodeSliceI32(data []byte, limit uint64) ([]int32, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%4 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]int32, len(data)/4)
	for index := range values {
		_part := data[index*4:]
		values[index] = int32(binary.LittleEndian.Uint32(_part))
	}
	return values, nil
}
func sizeU32(_ uint32, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 4) }
func encodeU32(value uint32, limit uint64) ([]byte, error) {
	if limit < 4 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint32(nil, uint32(value)), nil
}
func decodeU32(data []byte, _ uint64) (uint32, error) {
	if len(data) != 4 {
		return 0, rt.ErrProtocol
	}
	return uint32(binary.LittleEndian.Uint32(data)), nil
}
func sizeSliceU32(value []uint32, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 4)
}
func encodeSliceU32(values []uint32, limit uint64) ([]byte, error) {
	size, err := sizeSliceU32(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint32(data, uint32(value))
	}
	return data, nil
}
func decodeSliceU32(data []byte, limit uint64) ([]uint32, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%4 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]uint32, len(data)/4)
	for index := range values {
		_part := data[index*4:]
		values[index] = uint32(binary.LittleEndian.Uint32(_part))
	}
	return values, nil
}
func sizeI64(_ int64, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 8) }
func encodeI64(value int64, limit uint64) ([]byte, error) {
	if limit < 8 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint64(nil, uint64(value)), nil
}
func decodeI64(data []byte, _ uint64) (int64, error) {
	if len(data) != 8 {
		return 0, rt.ErrProtocol
	}
	return int64(binary.LittleEndian.Uint64(data)), nil
}
func sizeSliceI64(value []int64, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 8)
}
func encodeSliceI64(values []int64, limit uint64) ([]byte, error) {
	size, err := sizeSliceI64(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint64(data, uint64(value))
	}
	return data, nil
}
func decodeSliceI64(data []byte, limit uint64) ([]int64, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%8 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]int64, len(data)/8)
	for index := range values {
		_part := data[index*8:]
		values[index] = int64(binary.LittleEndian.Uint64(_part))
	}
	return values, nil
}
func sizeU64(_ uint64, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 8) }
func encodeU64(value uint64, limit uint64) ([]byte, error) {
	if limit < 8 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint64(nil, uint64(value)), nil
}
func decodeU64(data []byte, _ uint64) (uint64, error) {
	if len(data) != 8 {
		return 0, rt.ErrProtocol
	}
	return uint64(binary.LittleEndian.Uint64(data)), nil
}
func sizeSliceU64(value []uint64, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 8)
}
func encodeSliceU64(values []uint64, limit uint64) ([]byte, error) {
	size, err := sizeSliceU64(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint64(data, uint64(value))
	}
	return data, nil
}
func decodeSliceU64(data []byte, limit uint64) ([]uint64, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%8 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]uint64, len(data)/8)
	for index := range values {
		_part := data[index*8:]
		values[index] = uint64(binary.LittleEndian.Uint64(_part))
	}
	return values, nil
}
func sizeF32(_ float32, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 4) }
func encodeF32(value float32, limit uint64) ([]byte, error) {
	if limit < 4 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint32(nil, math.Float32bits(value)), nil
}
func decodeF32(data []byte, _ uint64) (float32, error) {
	if len(data) != 4 {
		return 0, rt.ErrProtocol
	}
	return math.Float32frombits(binary.LittleEndian.Uint32(data)), nil
}
func sizeSliceF32(value []float32, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 4)
}
func encodeSliceF32(values []float32, limit uint64) ([]byte, error) {
	size, err := sizeSliceF32(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint32(data, math.Float32bits(value))
	}
	return data, nil
}
func decodeSliceF32(data []byte, limit uint64) ([]float32, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%4 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]float32, len(data)/4)
	for index := range values {
		_part := data[index*4:]
		values[index] = math.Float32frombits(binary.LittleEndian.Uint32(_part))
	}
	return values, nil
}
func sizeF64(_ float64, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 8) }
func encodeF64(value float64, limit uint64) ([]byte, error) {
	if limit < 8 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint64(nil, math.Float64bits(value)), nil
}
func decodeF64(data []byte, _ uint64) (float64, error) {
	if len(data) != 8 {
		return 0, rt.ErrProtocol
	}
	return math.Float64frombits(binary.LittleEndian.Uint64(data)), nil
}
func sizeSliceF64(value []float64, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 8)
}
func encodeSliceF64(values []float64, limit uint64) ([]byte, error) {
	size, err := sizeSliceF64(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint64(data, math.Float64bits(value))
	}
	return data, nil
}
func decodeSliceF64(data []byte, limit uint64) ([]float64, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%8 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]float64, len(data)/8)
	for index := range values {
		_part := data[index*8:]
		values[index] = math.Float64frombits(binary.LittleEndian.Uint64(_part))
	}
	return values, nil
}
func (l *Library) ObfuscateSQL(_ctx context.Context, _arg0 string) (string, error) {
	if _err := l.admission(_ctx); _err != nil {
		return "", _err
	}
	defer l.life.Leave()
	var _size uint64
	var _err error
	_part0, _err := sizeString(_arg0, l.options.MaxInput)
	if _err != nil {
		return "", _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part0)
	if _err != nil {
		return "", _err
	}
	if !utf8.ValidString(_arg0) {
		return "", &rt.AppError{Op: "encode", Status: rt.ErrArg, Message: "invalid UTF-8"}
	}
	var _output string
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("obfuscate_sql", func(_call *rt.Call) error {
			if _inputErr := _call.PrepareInput(_size); _inputErr != nil {
				return _inputErr
			}
			_pointer0, _putErr := _call.PutString(_arg0)
			if _putErr != nil {
				return _putErr
			}
			_status := rt.Status(_guest.module.Xcocoon_obfuscate_sql(int32(_pointer0), int32(len(_arg0))))
			_reply, _resultErr := _call.ResultView("obfuscate_sql", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeString(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (l *Library) ObfuscateTraces(_ctx context.Context, _arg0 []byte) ([]byte, error) {
	if _err := l.admission(_ctx); _err != nil {
		return nil, _err
	}
	defer l.life.Leave()
	var _size uint64
	var _err error
	_part0, _err := sizeBytes(_arg0, l.options.MaxInput)
	if _err != nil {
		return nil, _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part0)
	if _err != nil {
		return nil, _err
	}
	_data0, _err := encodeBytes(_arg0, l.options.MaxInput)
	if _err != nil {
		return nil, _err
	}
	var _output []byte
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("obfuscate_traces", func(_call *rt.Call) error {
			if _inputErr := _call.PrepareInput(_size); _inputErr != nil {
				return _inputErr
			}
			_pointer0, _putErr := _call.PutBytes(_data0)
			if _putErr != nil {
				return _putErr
			}
			_status := rt.Status(_guest.module.Xcocoon_obfuscate_traces(int32(_pointer0), int32(len(_data0))))
			_reply, _resultErr := _call.ResultView("obfuscate_traces", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeBytes(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}

type Sketch struct {
	_       rt.NoCopy
	library *Library
	guest   *guest
	owner   *rt.Resource[Sketch]
}

func (l *Library) NewSketch() (*Sketch, error) {
	if l == nil {
		return nil, rt.ErrClosed
	}
	if _err := l.life.Enter(); _err != nil {
		return nil, _err
	}
	defer l.life.Leave()
	var _err error
	var _output uint64
	_guest, _err := l.getHome()
	if _err != nil {
		return nil, _err
	}
	_err = _guest.instance.Call("new", func(_call *rt.Call) error {
		_status := rt.Status(_guest.module.Xcocoon_sketch_new())
		_reply, _resultErr := _call.ResultView("new", _status)
		if _resultErr != nil {
			return _resultErr
		}
		_decoded, _decodeErr := decodeU64(_reply, l.options.MaxOutput)
		if _decodeErr != nil {
			return _decodeErr
		}
		_output = _decoded
		return nil
	})
	if _err != nil {
		return nil, _err
	}
	_owner, _ownErr := rt.NewResource[Sketch](_guest.instance, _output, func(_handle uint64) error {
		return _guest.instance.Call("close", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_sketch_close(int64(_handle)))
			return _call.ResultUnit("close", _status)
		})
	})
	if _ownErr != nil {
		return nil, _ownErr
	}
	return &Sketch{library: l, guest: _guest, owner: _owner}, nil
}
func (r *Sketch) Add(_arg0 float64) error {
	if r == nil || r.library == nil || r.owner == nil {
		return &rt.HandleError{Op: "add", Reason: "nil resource"}
	}
	l := r.library
	if _err := l.life.Enter(); _err != nil {
		return _err
	}
	defer l.life.Leave()
	var _err error
	_err = r.owner.Use("add", func(_instance *rt.Instance, _handle uint64) error {
		_guest := r.guest
		return _instance.Call("add", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_sketch_add(int64(_handle), _arg0))
			_reply, _resultErr := _call.ResultView("add", _status)
			if _resultErr != nil {
				return _resultErr
			}
			if len(_reply) != 0 {
				return rt.ErrProtocol
			}
			return nil
		})
	})
	return _err
}
func (r *Sketch) AddMany(_arg0 []float64) error {
	if r == nil || r.library == nil || r.owner == nil {
		return &rt.HandleError{Op: "add_many", Reason: "nil resource"}
	}
	l := r.library
	if _err := l.life.Enter(); _err != nil {
		return _err
	}
	defer l.life.Leave()
	var _size uint64
	var _err error
	_part0, _err := sizeSliceF64(_arg0, l.options.MaxInput)
	if _err != nil {
		return _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part0)
	if _err != nil {
		return _err
	}
	_data0, _err := encodeSliceF64(_arg0, l.options.MaxInput)
	if _err != nil {
		return _err
	}
	_err = r.owner.Use("add_many", func(_instance *rt.Instance, _handle uint64) error {
		_guest := r.guest
		return _instance.Call("add_many", func(_call *rt.Call) error {
			if _inputErr := _call.PrepareInput(_size); _inputErr != nil {
				return _inputErr
			}
			_pointer0, _putErr := _call.PutBytes(_data0)
			if _putErr != nil {
				return _putErr
			}
			_status := rt.Status(_guest.module.Xcocoon_sketch_add_many(int64(_handle), int32(_pointer0), int32(len(_data0))))
			_reply, _resultErr := _call.ResultView("add_many", _status)
			if _resultErr != nil {
				return _resultErr
			}
			if len(_reply) != 0 {
				return rt.ErrProtocol
			}
			return nil
		})
	})
	return _err
}
func (r *Sketch) Count() (float64, error) {
	if r == nil || r.library == nil || r.owner == nil {
		return 0, &rt.HandleError{Op: "count", Reason: "nil resource"}
	}
	l := r.library
	if _err := l.life.Enter(); _err != nil {
		return 0, _err
	}
	defer l.life.Leave()
	var _err error
	var _output float64
	_err = r.owner.Use("count", func(_instance *rt.Instance, _handle uint64) error {
		_guest := r.guest
		return _instance.Call("count", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_sketch_count(int64(_handle)))
			_reply, _resultErr := _call.ResultView("count", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeF64(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (r *Sketch) Encode() ([]byte, error) {
	if r == nil || r.library == nil || r.owner == nil {
		return nil, &rt.HandleError{Op: "encode", Reason: "nil resource"}
	}
	l := r.library
	if _err := l.life.Enter(); _err != nil {
		return nil, _err
	}
	defer l.life.Leave()
	var _err error
	var _output []byte
	_err = r.owner.Use("encode", func(_instance *rt.Instance, _handle uint64) error {
		_guest := r.guest
		return _instance.Call("encode", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_sketch_encode(int64(_handle)))
			_reply, _resultErr := _call.ResultView("encode", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeBytes(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (r *Sketch) Close() error {
	if r == nil || r.library == nil || r.owner == nil {
		return &rt.HandleError{Op: "close", Reason: "nil resource"}
	}
	return r.owner.Close()
}
