// Code generated by cocoon. DO NOT EDIT.
package dd

import (
	wasm "cocoon.dev/cocoon/examples/datadog/go/dd/internal/wasm"
	"cocoon.dev/cocoon/rt"
)

type module struct{ *wasm.Module }

func (m *module) Memory() []byte             { return *m.Xmemory().Slice() }
func (m *module) Version() uint32            { return uint32(m.Xcocoon_abi_version()) }
func (m *module) Schema() uint64             { return uint64(m.Xcocoon_schema_hash()) }
func (m *module) Init()                      { m.Xcocoon_init() }
func (m *module) Reserve(size uint32) uint32 { return uint32(m.Xcocoon_in_reserve(int32(size))) }
func (m *module) Output() uint32             { return uint32(m.Xcocoon_out()) }
func (m *module) Trim(keep uint32)           { m.Xcocoon_trim(int32(keep)) }

type imports struct{ host *rt.Host }

func (h imports) Xlog(level, pointer, size int32) { h.host.Log(level, uint32(pointer), uint32(size)) }
func (h imports) Xrandom_get(pointer, size int32) int32 {
	return h.host.RandomGet(uint32(pointer), uint32(size))
}
func newModule(options Options) (*module, *rt.Host) {
	host := rt.NewHost(options.Logger)
	raw := wasm.New(imports{host: host})
	adapter := &module{Module: raw}
	host.Bind(adapter)
	return adapter, host
}
