// Code generated by cocoon. DO NOT EDIT.
package compute

import (
	"context"
	"dario.cat/cocoon/rt"
	"encoding/binary"
	"log/slog"
	"math"
	"runtime"
	"sync"
	"unicode/utf8"
)

const schemaHash uint64 = 4076813288107292652
const maximumMemory uint64 = 16777216

type Options struct {
	Logger              *slog.Logger
	MaxInput, MaxOutput uint64
	Instances           int
}
type guest struct {
	module   *module
	instance *rt.Instance
}

func (g *guest) close() { g.instance.Close(); g.module = nil }

type Library struct {
	pool    *rt.Pool[guest]
	home    *guest
	options Options
	homeMu  sync.Mutex
	life    rt.Lifecycle
}

func Open(options Options) (*Library, error) {
	if options.MaxInput == 0 {
		options.MaxInput = 65536
	}
	if options.MaxOutput == 0 {
		options.MaxOutput = 65536
	}
	if options.MaxInput > 65536 || options.MaxOutput > 65536 || options.Instances < 0 {
		return nil, rt.ErrTooLarge
	}
	if options.Instances == 0 {
		options.Instances = runtime.GOMAXPROCS(0)
		options.Instances = 1
	}
	l := &Library{options: options}
	pool, err := rt.NewPool(options.Instances, l.newGuest, func(g *guest) bool { return g.instance.Recycle(65536, maximumMemory) }, func(g *guest) { g.close() })
	if err != nil {
		return nil, err
	}
	l.pool = pool
	return l, nil
}
func (l *Library) newGuest() (_guest *guest, _err error) {
	defer func() {
		if value := recover(); value != nil {
			_err = rt.Classify("construct", value, "")
		}
	}()
	raw, host := newModule(l.options)
	instance, err := rt.NewInstance(raw, schemaHash, rt.Limits{MaxInput: l.options.MaxInput, MaxOutput: l.options.MaxOutput, MaxMemory: maximumMemory}, host)
	if err != nil {
		return nil, err
	}
	return &guest{module: raw, instance: instance}, nil
}
func (l *Library) admission(ctx context.Context) error {
	if l == nil {
		return rt.ErrClosed
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	return l.life.Enter()
}
func (l *Library) getHome() (*guest, error) {
	l.homeMu.Lock()
	defer l.homeMu.Unlock()
	if l.home != nil && !l.home.instance.Healthy() {
		l.home.close()
		l.home = nil
	}
	if l.home == nil {
		home, err := l.newGuest()
		if err != nil {
			return nil, err
		}
		l.home = home
	}
	return l.home, nil
}
func (l *Library) Close() error {
	if l == nil {
		return nil
	}
	return l.life.Close(func() error {
		err := l.pool.Close()
		l.homeMu.Lock()
		defer l.homeMu.Unlock()
		if l.home != nil {
			l.home.close()
			l.home = nil
		}
		return err
	})
}
func boolParam(value bool) int32 {
	if value {
		return 1
	}
	return 0
}
func sizeString(value string, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 1)
}
func sizeBytes(value []byte, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 1)
}
func encodeString(value string, limit uint64) ([]byte, error) {
	if _, err := sizeString(value, limit); err != nil {
		return nil, err
	}
	if !utf8.ValidString(value) {
		return nil, &rt.AppError{Status: rt.ErrArg, Op: "encode", Message: "invalid UTF-8"}
	}
	return []byte(value), nil
}
func encodeBytes(value []byte, limit uint64) ([]byte, error) {
	if _, err := sizeBytes(value, limit); err != nil {
		return nil, err
	}
	return value, nil
}
func decodeString(data []byte, limit uint64) (string, error) {
	if uint64(len(data)) > limit {
		return "", rt.ErrTooLarge
	}
	if !utf8.Valid(data) {
		return "", rt.ErrProtocol
	}
	return string(data), nil
}
func decodeBytes(data []byte, limit uint64) ([]byte, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	return append([]byte(nil), data...), nil
}
func sizeBool(_ bool, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 1) }
func encodeBool(value bool, limit uint64) ([]byte, error) {
	if limit < 1 {
		return nil, rt.ErrTooLarge
	}
	return []byte{byte(boolParam(value))}, nil
}
func decodeBool(data []byte, _ uint64) (bool, error) {
	if len(data) != 1 || data[0] > 1 {
		return false, rt.ErrProtocol
	}
	return data[0] == 1, nil
}
func sizeI32(_ int32, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 4) }
func encodeI32(value int32, limit uint64) ([]byte, error) {
	if limit < 4 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint32(nil, uint32(value)), nil
}
func decodeI32(data []byte, _ uint64) (int32, error) {
	if len(data) != 4 {
		return 0, rt.ErrProtocol
	}
	return int32(binary.LittleEndian.Uint32(data)), nil
}
func sizeSliceI32(value []int32, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 4)
}
func encodeSliceI32(values []int32, limit uint64) ([]byte, error) {
	size, err := sizeSliceI32(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint32(data, uint32(value))
	}
	return data, nil
}
func decodeSliceI32(data []byte, limit uint64) ([]int32, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%4 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]int32, len(data)/4)
	for index := range values {
		_part := data[index*4:]
		values[index] = int32(binary.LittleEndian.Uint32(_part))
	}
	return values, nil
}
func sizeU32(_ uint32, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 4) }
func encodeU32(value uint32, limit uint64) ([]byte, error) {
	if limit < 4 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint32(nil, uint32(value)), nil
}
func decodeU32(data []byte, _ uint64) (uint32, error) {
	if len(data) != 4 {
		return 0, rt.ErrProtocol
	}
	return uint32(binary.LittleEndian.Uint32(data)), nil
}
func sizeSliceU32(value []uint32, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 4)
}
func encodeSliceU32(values []uint32, limit uint64) ([]byte, error) {
	size, err := sizeSliceU32(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint32(data, uint32(value))
	}
	return data, nil
}
func decodeSliceU32(data []byte, limit uint64) ([]uint32, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%4 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]uint32, len(data)/4)
	for index := range values {
		_part := data[index*4:]
		values[index] = uint32(binary.LittleEndian.Uint32(_part))
	}
	return values, nil
}
func sizeI64(_ int64, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 8) }
func encodeI64(value int64, limit uint64) ([]byte, error) {
	if limit < 8 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint64(nil, uint64(value)), nil
}
func decodeI64(data []byte, _ uint64) (int64, error) {
	if len(data) != 8 {
		return 0, rt.ErrProtocol
	}
	return int64(binary.LittleEndian.Uint64(data)), nil
}
func sizeSliceI64(value []int64, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 8)
}
func encodeSliceI64(values []int64, limit uint64) ([]byte, error) {
	size, err := sizeSliceI64(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint64(data, uint64(value))
	}
	return data, nil
}
func decodeSliceI64(data []byte, limit uint64) ([]int64, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%8 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]int64, len(data)/8)
	for index := range values {
		_part := data[index*8:]
		values[index] = int64(binary.LittleEndian.Uint64(_part))
	}
	return values, nil
}
func sizeU64(_ uint64, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 8) }
func encodeU64(value uint64, limit uint64) ([]byte, error) {
	if limit < 8 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint64(nil, uint64(value)), nil
}
func decodeU64(data []byte, _ uint64) (uint64, error) {
	if len(data) != 8 {
		return 0, rt.ErrProtocol
	}
	return uint64(binary.LittleEndian.Uint64(data)), nil
}
func sizeSliceU64(value []uint64, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 8)
}
func encodeSliceU64(values []uint64, limit uint64) ([]byte, error) {
	size, err := sizeSliceU64(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint64(data, uint64(value))
	}
	return data, nil
}
func decodeSliceU64(data []byte, limit uint64) ([]uint64, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%8 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]uint64, len(data)/8)
	for index := range values {
		_part := data[index*8:]
		values[index] = uint64(binary.LittleEndian.Uint64(_part))
	}
	return values, nil
}
func sizeF32(_ float32, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 4) }
func encodeF32(value float32, limit uint64) ([]byte, error) {
	if limit < 4 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint32(nil, math.Float32bits(value)), nil
}
func decodeF32(data []byte, _ uint64) (float32, error) {
	if len(data) != 4 {
		return 0, rt.ErrProtocol
	}
	return math.Float32frombits(binary.LittleEndian.Uint32(data)), nil
}
func sizeSliceF32(value []float32, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 4)
}
func encodeSliceF32(values []float32, limit uint64) ([]byte, error) {
	size, err := sizeSliceF32(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint32(data, math.Float32bits(value))
	}
	return data, nil
}
func decodeSliceF32(data []byte, limit uint64) ([]float32, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%4 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]float32, len(data)/4)
	for index := range values {
		_part := data[index*4:]
		values[index] = math.Float32frombits(binary.LittleEndian.Uint32(_part))
	}
	return values, nil
}
func sizeF64(_ float64, limit uint64) (uint64, error) { return rt.InputSize(limit, 1, 8) }
func encodeF64(value float64, limit uint64) ([]byte, error) {
	if limit < 8 {
		return nil, rt.ErrTooLarge
	}
	return binary.LittleEndian.AppendUint64(nil, math.Float64bits(value)), nil
}
func decodeF64(data []byte, _ uint64) (float64, error) {
	if len(data) != 8 {
		return 0, rt.ErrProtocol
	}
	return math.Float64frombits(binary.LittleEndian.Uint64(data)), nil
}
func sizeSliceF64(value []float64, limit uint64) (uint64, error) {
	return rt.InputSize(limit, uint64(len(value)), 8)
}
func encodeSliceF64(values []float64, limit uint64) ([]byte, error) {
	size, err := sizeSliceF64(values, limit)
	if err != nil {
		return nil, err
	}
	data := make([]byte, 0, int(size))
	for _, value := range values {
		data = binary.LittleEndian.AppendUint64(data, math.Float64bits(value))
	}
	return data, nil
}
func decodeSliceF64(data []byte, limit uint64) ([]float64, error) {
	if uint64(len(data)) > limit {
		return nil, rt.ErrTooLarge
	}
	if len(data)%8 != 0 {
		return nil, rt.ErrProtocol
	}
	values := make([]float64, len(data)/8)
	for index := range values {
		_part := data[index*8:]
		values[index] = math.Float64frombits(binary.LittleEndian.Uint64(_part))
	}
	return values, nil
}

type Numbers struct {
	Signed32   int32
	Unsigned32 uint32
	Signed64   int64
	Unsigned64 uint64
	Float32    float32
	Float64    float64
	Enabled    bool
}

func sizeNumbers(value Numbers, limit uint64) (uint64, error) {
	total, err := rt.InputSize(limit, 7, 8, 4)
	if err != nil {
		return 0, err
	}
	part0, err := sizeI32(value.Signed32, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part0)
	if err != nil {
		return 0, err
	}
	part1, err := sizeU32(value.Unsigned32, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part1)
	if err != nil {
		return 0, err
	}
	part2, err := sizeI64(value.Signed64, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part2)
	if err != nil {
		return 0, err
	}
	part3, err := sizeU64(value.Unsigned64, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part3)
	if err != nil {
		return 0, err
	}
	part4, err := sizeF32(value.Float32, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part4)
	if err != nil {
		return 0, err
	}
	part5, err := sizeF64(value.Float64, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part5)
	if err != nil {
		return 0, err
	}
	part6, err := sizeBool(value.Enabled, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part6)
	if err != nil {
		return 0, err
	}
	return total, nil
}
func encodeNumbers(value Numbers, limit uint64) ([]byte, error) {
	if _, err := sizeNumbers(value, limit); err != nil {
		return nil, err
	}
	part0, err := encodeI32(value.Signed32, limit)
	if err != nil {
		return nil, err
	}
	part1, err := encodeU32(value.Unsigned32, limit)
	if err != nil {
		return nil, err
	}
	part2, err := encodeI64(value.Signed64, limit)
	if err != nil {
		return nil, err
	}
	part3, err := encodeU64(value.Unsigned64, limit)
	if err != nil {
		return nil, err
	}
	part4, err := encodeF32(value.Float32, limit)
	if err != nil {
		return nil, err
	}
	part5, err := encodeF64(value.Float64, limit)
	if err != nil {
		return nil, err
	}
	part6, err := encodeBool(value.Enabled, limit)
	if err != nil {
		return nil, err
	}
	return rt.EncodeRecord([]rt.Field{{ID: 1, Data: part0}, {ID: 2, Data: part1}, {ID: 3, Data: part2}, {ID: 4, Data: part3}, {ID: 5, Data: part4}, {ID: 6, Data: part5}, {ID: 7, Data: part6}}, limit)
}
func decodeNumbers(data []byte, limit uint64) (Numbers, error) {
	var value Numbers
	fields, err := rt.DecodeRecord(data, 7, limit)
	if err != nil {
		return value, err
	}
	value.Signed32, err = decodeI32(fields[0], limit)
	if err != nil {
		return value, err
	}
	value.Unsigned32, err = decodeU32(fields[1], limit)
	if err != nil {
		return value, err
	}
	value.Signed64, err = decodeI64(fields[2], limit)
	if err != nil {
		return value, err
	}
	value.Unsigned64, err = decodeU64(fields[3], limit)
	if err != nil {
		return value, err
	}
	value.Float32, err = decodeF32(fields[4], limit)
	if err != nil {
		return value, err
	}
	value.Float64, err = decodeF64(fields[5], limit)
	if err != nil {
		return value, err
	}
	value.Enabled, err = decodeBool(fields[6], limit)
	if err != nil {
		return value, err
	}
	return value, nil
}

type Payload struct {
	Label      string
	Data       []byte
	Numbers    Numbers
	Signed32   []int32
	Unsigned32 []uint32
	Signed64   []int64
	Unsigned64 []uint64
	Float32    []float32
	Float64    []float64
}

func sizePayload(value Payload, limit uint64) (uint64, error) {
	total, err := rt.InputSize(limit, 9, 8, 4)
	if err != nil {
		return 0, err
	}
	part0, err := sizeString(value.Label, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part0)
	if err != nil {
		return 0, err
	}
	part1, err := sizeBytes(value.Data, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part1)
	if err != nil {
		return 0, err
	}
	part2, err := sizeNumbers(value.Numbers, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part2)
	if err != nil {
		return 0, err
	}
	part3, err := sizeSliceI32(value.Signed32, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part3)
	if err != nil {
		return 0, err
	}
	part4, err := sizeSliceU32(value.Unsigned32, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part4)
	if err != nil {
		return 0, err
	}
	part5, err := sizeSliceI64(value.Signed64, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part5)
	if err != nil {
		return 0, err
	}
	part6, err := sizeSliceU64(value.Unsigned64, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part6)
	if err != nil {
		return 0, err
	}
	part7, err := sizeSliceF32(value.Float32, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part7)
	if err != nil {
		return 0, err
	}
	part8, err := sizeSliceF64(value.Float64, limit)
	if err != nil {
		return 0, err
	}
	total, err = rt.InputSize(limit, 1, total, part8)
	if err != nil {
		return 0, err
	}
	return total, nil
}
func encodePayload(value Payload, limit uint64) ([]byte, error) {
	if _, err := sizePayload(value, limit); err != nil {
		return nil, err
	}
	part0, err := encodeString(value.Label, limit)
	if err != nil {
		return nil, err
	}
	part1, err := encodeBytes(value.Data, limit)
	if err != nil {
		return nil, err
	}
	part2, err := encodeNumbers(value.Numbers, limit)
	if err != nil {
		return nil, err
	}
	part3, err := encodeSliceI32(value.Signed32, limit)
	if err != nil {
		return nil, err
	}
	part4, err := encodeSliceU32(value.Unsigned32, limit)
	if err != nil {
		return nil, err
	}
	part5, err := encodeSliceI64(value.Signed64, limit)
	if err != nil {
		return nil, err
	}
	part6, err := encodeSliceU64(value.Unsigned64, limit)
	if err != nil {
		return nil, err
	}
	part7, err := encodeSliceF32(value.Float32, limit)
	if err != nil {
		return nil, err
	}
	part8, err := encodeSliceF64(value.Float64, limit)
	if err != nil {
		return nil, err
	}
	return rt.EncodeRecord([]rt.Field{{ID: 1, Data: part0}, {ID: 2, Data: part1}, {ID: 3, Data: part2}, {ID: 4, Data: part3}, {ID: 5, Data: part4}, {ID: 6, Data: part5}, {ID: 7, Data: part6}, {ID: 8, Data: part7}, {ID: 9, Data: part8}}, limit)
}
func decodePayload(data []byte, limit uint64) (Payload, error) {
	var value Payload
	fields, err := rt.DecodeRecord(data, 9, limit)
	if err != nil {
		return value, err
	}
	value.Label, err = decodeString(fields[0], limit)
	if err != nil {
		return value, err
	}
	value.Data, err = decodeBytes(fields[1], limit)
	if err != nil {
		return value, err
	}
	value.Numbers, err = decodeNumbers(fields[2], limit)
	if err != nil {
		return value, err
	}
	value.Signed32, err = decodeSliceI32(fields[3], limit)
	if err != nil {
		return value, err
	}
	value.Unsigned32, err = decodeSliceU32(fields[4], limit)
	if err != nil {
		return value, err
	}
	value.Signed64, err = decodeSliceI64(fields[5], limit)
	if err != nil {
		return value, err
	}
	value.Unsigned64, err = decodeSliceU64(fields[6], limit)
	if err != nil {
		return value, err
	}
	value.Float32, err = decodeSliceF32(fields[7], limit)
	if err != nil {
		return value, err
	}
	value.Float64, err = decodeSliceF64(fields[8], limit)
	if err != nil {
		return value, err
	}
	return value, nil
}
func (l *Library) Echo(_ctx context.Context, _arg0 string) (string, error) {
	if _err := l.admission(_ctx); _err != nil {
		return "", _err
	}
	defer l.life.Leave()
	var _size uint64
	var _err error
	_part0, _err := sizeString(_arg0, l.options.MaxInput)
	if _err != nil {
		return "", _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part0)
	if _err != nil {
		return "", _err
	}
	if !utf8.ValidString(_arg0) {
		return "", &rt.AppError{Op: "encode", Status: rt.ErrArg, Message: "invalid UTF-8"}
	}
	var _output string
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("echo", func(_call *rt.Call) error {
			if _inputErr := _call.PrepareInput(_size); _inputErr != nil {
				return _inputErr
			}
			_pointer0, _putErr := _call.PutString(_arg0)
			if _putErr != nil {
				return _putErr
			}
			_status := rt.Status(_guest.module.Xcocoon_echo(int32(_pointer0), int32(len(_arg0))))
			_reply, _resultErr := _call.ResultView("echo", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeString(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (l *Library) Join(_ctx context.Context, _arg0 string, _arg1 string) (string, error) {
	if _err := l.admission(_ctx); _err != nil {
		return "", _err
	}
	defer l.life.Leave()
	var _size uint64
	var _err error
	_part0, _err := sizeString(_arg0, l.options.MaxInput)
	if _err != nil {
		return "", _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part0)
	if _err != nil {
		return "", _err
	}
	_part1, _err := sizeString(_arg1, l.options.MaxInput)
	if _err != nil {
		return "", _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part1)
	if _err != nil {
		return "", _err
	}
	if !utf8.ValidString(_arg0) {
		return "", &rt.AppError{Op: "encode", Status: rt.ErrArg, Message: "invalid UTF-8"}
	}
	if !utf8.ValidString(_arg1) {
		return "", &rt.AppError{Op: "encode", Status: rt.ErrArg, Message: "invalid UTF-8"}
	}
	var _output string
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("join", func(_call *rt.Call) error {
			if _inputErr := _call.PrepareInput(_size); _inputErr != nil {
				return _inputErr
			}
			_pointer0, _putErr := _call.PutString(_arg0)
			if _putErr != nil {
				return _putErr
			}
			_pointer1, _putErr := _call.PutString(_arg1)
			if _putErr != nil {
				return _putErr
			}
			_status := rt.Status(_guest.module.Xcocoon_join(int32(_pointer0), int32(len(_arg0)), int32(_pointer1), int32(len(_arg1))))
			_reply, _resultErr := _call.ResultView("join", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeString(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (l *Library) Bounce(_ctx context.Context, _arg0 Payload) (Payload, error) {
	if _err := l.admission(_ctx); _err != nil {
		return Payload{}, _err
	}
	defer l.life.Leave()
	var _size uint64
	var _err error
	_part0, _err := sizePayload(_arg0, l.options.MaxInput)
	if _err != nil {
		return Payload{}, _err
	}
	_size, _err = rt.InputSize(l.options.MaxInput, 1, _size, _part0)
	if _err != nil {
		return Payload{}, _err
	}
	_data0, _err := encodePayload(_arg0, l.options.MaxInput)
	if _err != nil {
		return Payload{}, _err
	}
	var _output Payload
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("bounce", func(_call *rt.Call) error {
			if _inputErr := _call.PrepareInput(_size); _inputErr != nil {
				return _inputErr
			}
			_pointer0, _putErr := _call.PutBytes(_data0)
			if _putErr != nil {
				return _putErr
			}
			_status := rt.Status(_guest.module.Xcocoon_bounce(int32(_pointer0), int32(len(_data0))))
			_reply, _resultErr := _call.ResultView("bounce", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodePayload(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (l *Library) ScalarValues(_ctx context.Context, _arg0 int32, _arg1 uint32, _arg2 int64, _arg3 uint64, _arg4 float32, _arg5 float64, _arg6 bool) (Numbers, error) {
	if _err := l.admission(_ctx); _err != nil {
		return Numbers{}, _err
	}
	defer l.life.Leave()
	var _err error
	var _output Numbers
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("scalar_values", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_scalar_values(_arg0, int32(_arg1), _arg2, int64(_arg3), _arg4, _arg5, boolParam(_arg6)))
			_reply, _resultErr := _call.ResultView("scalar_values", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeNumbers(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (l *Library) TestTrap(_ctx context.Context, _arg0 uint32) error {
	if _err := l.admission(_ctx); _err != nil {
		return _err
	}
	defer l.life.Leave()
	var _err error
	_err = l.pool.Do(_ctx, func(_guest *guest) error {
		return _guest.instance.Call("test_trap", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_test_trap(int32(_arg0)))
			_reply, _resultErr := _call.ResultView("test_trap", _status)
			if _resultErr != nil {
				return _resultErr
			}
			if len(_reply) != 0 {
				return rt.ErrProtocol
			}
			return nil
		})
	})
	return _err
}

type Counter struct {
	_       rt.NoCopy
	library *Library
	guest   *guest
	owner   *rt.Resource[Counter]
}

func (l *Library) NewCounter(_arg0 uint64) (*Counter, error) {
	if l == nil {
		return nil, rt.ErrClosed
	}
	if _err := l.life.Enter(); _err != nil {
		return nil, _err
	}
	defer l.life.Leave()
	var _err error
	var _output uint64
	_guest, _err := l.getHome()
	if _err != nil {
		return nil, _err
	}
	_err = _guest.instance.Call("new", func(_call *rt.Call) error {
		_status := rt.Status(_guest.module.Xcocoon_counter_new(int64(_arg0)))
		_reply, _resultErr := _call.ResultView("new", _status)
		if _resultErr != nil {
			return _resultErr
		}
		_decoded, _decodeErr := decodeU64(_reply, l.options.MaxOutput)
		if _decodeErr != nil {
			return _decodeErr
		}
		_output = _decoded
		return nil
	})
	if _err != nil {
		return nil, _err
	}
	_owner, _ownErr := rt.NewResource[Counter](_guest.instance, _output, func(_handle uint64) error {
		return _guest.instance.Call("close", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_counter_close(int64(_handle)))
			return _call.ResultUnit("close", _status)
		})
	})
	if _ownErr != nil {
		return nil, _ownErr
	}
	return &Counter{library: l, guest: _guest, owner: _owner}, nil
}
func (r *Counter) Add(_arg0 uint64) (uint64, error) {
	if r == nil || r.library == nil || r.owner == nil {
		return 0, &rt.HandleError{Op: "add", Reason: "nil resource"}
	}
	l := r.library
	if _err := l.life.Enter(); _err != nil {
		return 0, _err
	}
	defer l.life.Leave()
	var _err error
	var _output uint64
	_err = r.owner.Use("add", func(_instance *rt.Instance, _handle uint64) error {
		_guest := r.guest
		return _instance.Call("add", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_counter_add(int64(_handle), int64(_arg0)))
			_reply, _resultErr := _call.ResultView("add", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeU64(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (r *Counter) Count() (uint64, error) {
	if r == nil || r.library == nil || r.owner == nil {
		return 0, &rt.HandleError{Op: "count", Reason: "nil resource"}
	}
	l := r.library
	if _err := l.life.Enter(); _err != nil {
		return 0, _err
	}
	defer l.life.Leave()
	var _err error
	var _output uint64
	_err = r.owner.Use("count", func(_instance *rt.Instance, _handle uint64) error {
		_guest := r.guest
		return _instance.Call("count", func(_call *rt.Call) error {
			_status := rt.Status(_guest.module.Xcocoon_counter_count(int64(_handle)))
			_reply, _resultErr := _call.ResultView("count", _status)
			if _resultErr != nil {
				return _resultErr
			}
			_decoded, _decodeErr := decodeU64(_reply, l.options.MaxOutput)
			if _decodeErr != nil {
				return _decodeErr
			}
			_output = _decoded
			return nil
		})
	})
	return _output, _err
}
func (r *Counter) Close() error {
	if r == nil || r.library == nil || r.owner == nil {
		return &rt.HandleError{Op: "close", Reason: "nil resource"}
	}
	return r.owner.Close()
}
