// Code generated by cocoon. DO NOT EDIT.
package compute

import (
	"dario.cat/cocoon/rt"
	"errors"
	"reflect"
	"runtime"
	"testing"
)

func TestGeneratedLimitsAndClose(t *testing.T) {
	t.Parallel()
	for _, options := range []Options{{MaxInput: 65537}, {MaxOutput: 65537}, {Instances: -1}} {
		if _, err := Open(options); !errors.Is(err, rt.ErrTooLarge) {
			t.Fatalf("invalid options: %v", err)
		}
	}
	l, err := Open(Options{Instances: 1})
	if err != nil {
		t.Fatal(err)
	}
	if err := l.Close(); err != nil {
		t.Fatal(err)
	}
	if err := l.Close(); err != nil {
		t.Fatal(err)
	}
	{
		_, err := l.Echo(t.Context(), "")
		if !errors.Is(err, rt.ErrClosed) {
			t.Fatalf("call after close: %v", err)
		}
	}
	{
		_, err := l.Join(t.Context(), "", "")
		if !errors.Is(err, rt.ErrClosed) {
			t.Fatalf("call after close: %v", err)
		}
	}
	{
		_, err := l.Bounce(t.Context(), Payload{})
		if !errors.Is(err, rt.ErrClosed) {
			t.Fatalf("call after close: %v", err)
		}
	}
	{
		_, err := l.ScalarValues(t.Context(), 0, 0, 0, 0, 0, 0, false)
		if !errors.Is(err, rt.ErrClosed) {
			t.Fatalf("call after close: %v", err)
		}
	}
	{
		err := l.TestTrap(t.Context(), 0)
		if !errors.Is(err, rt.ErrClosed) {
			t.Fatalf("call after close: %v", err)
		}
	}
	{
		_, err := l.NewCounter(0)
		if !errors.Is(err, rt.ErrClosed) {
			t.Fatalf("constructor after close: %v", err)
		}
	}
}
func TestGeneratedCounterOwnership(t *testing.T) {
	t.Parallel()
	l, err := Open(Options{Instances: 1})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := l.Close(); err != nil {
			t.Error(err)
		}
	})
	r, err := l.NewCounter(0)
	if err != nil {
		t.Fatal(err)
	}
	copyValue := reflect.New(reflect.TypeOf(r).Elem())
	copyValue.Elem().Set(reflect.ValueOf(r).Elem())
	alias, ok := copyValue.Interface().(*Counter)
	if !ok {
		t.Fatal("wrapper copy")
	}
	r = nil
	runtime.GC()
	runtime.Gosched()
	if err := alias.owner.Use("copy", func(*rt.Instance, uint64) error { return nil }); err != nil {
		t.Fatal(err)
	}
	if err := alias.Close(); err != nil {
		t.Fatal(err)
	}
	if err := alias.Close(); err != nil {
		t.Fatal(err)
	}
	var handleErr *rt.HandleError
	if err := alias.owner.Use("closed", func(*rt.Instance, uint64) error { t.Fatal("closed alias executed"); return nil }); !errors.As(err, &handleErr) {
		t.Fatalf("closed alias: %v", err)
	}
	faulted, err := l.NewCounter(0)
	if err != nil {
		t.Fatal(err)
	}
	faultErr := faulted.guest.instance.Call("fault", func(*rt.Call) error { panic("integer overflow") })
	var fault *rt.FaultError
	if !errors.As(faultErr, &fault) {
		t.Fatal(faultErr)
	}
	if err := faulted.owner.Use("faulted", func(*rt.Instance, uint64) error { t.Fatal("faulted resource executed"); return nil }); !errors.As(err, &handleErr) {
		t.Fatal(err)
	}
	replacement, err := l.NewCounter(0)
	if err != nil {
		t.Fatal(err)
	}
	if err := replacement.owner.Use("replacement", func(*rt.Instance, uint64) error { return nil }); err != nil {
		t.Fatal(err)
	}
	if err := faulted.Close(); err != nil && !errors.Is(err, rt.ErrClosed) && !errors.Is(err, rt.ErrPoisoned) {
		t.Fatal(err)
	}
	if err := l.Close(); err != nil {
		t.Fatal(err)
	}
	if err := replacement.owner.Use("library closed", func(*rt.Instance, uint64) error { t.Fatal("released resource executed"); return nil }); !errors.As(err, &handleErr) {
		t.Fatal(err)
	}
}
