// Code generated by cocoon. DO NOT EDIT.
package compute

import (
	"bytes"
	"dario.cat/cocoon/cocoontest"
	"dario.cat/cocoon/rt"
	_ "embed"
	"errors"
	"math"
	"testing"
)

//go:embed testdata/module.wasm
var generatedWasm []byte

type generatedCase struct {
	name string
	args []cocoontest.Arg
}

func newDifferential(t testing.TB) (*guest, *cocoontest.Guest) {
	t.Helper()
	l, err := Open(Options{Instances: 1})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := l.Close(); err != nil {
			t.Error(err)
		}
	})
	g, err := l.newGuest()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(g.close)
	reference := cocoontest.New(t, generatedWasm)
	for _, identity := range []struct {
		name string
		want uint64
	}{{"cocoon_abi_version", rt.ABIVersion}, {"cocoon_schema_hash", schemaHash}} {
		got, err := reference.Call(t.Context(), identity.name)
		if err != nil || len(got) != 1 || got[0] != identity.want {
			t.Fatalf("reference identity %s: %v %v", identity.name, got, err)
		}
	}
	if _, err := reference.Call(t.Context(), "cocoon_init"); err != nil {
		t.Fatal(err)
	}
	return g, reference
}
func compareOperation(t testing.TB, g *guest, reference *cocoontest.Guest, name string, args []cocoontest.Arg) (rt.Status, []byte) {
	t.Helper()
	var status rt.Status
	var output []byte
	err := g.instance.Call(name, func(call *rt.Call) error {
		var size uint64
		for _, arg := range args {
			if arg.Buffer {
				next, err := rt.InputSize(g.instanceLimits().MaxInput, 1, size, uint64(len(arg.Bytes)))
				if err != nil {
					return err
				}
				size = next
			}
		}
		if err := call.PrepareInput(size); err != nil {
			return err
		}
		pointers := make([]uint32, len(args))
		for index, arg := range args {
			if arg.Buffer {
				pointer, err := call.PutBytes(arg.Bytes)
				if err != nil {
					return err
				}
				pointers[index] = pointer
			}
		}
		status = generatedInvoke(g, name, args, pointers)
		var resultErr error
		output, resultErr = call.Result(name, status)
		return resultErr
	})
	limits := g.instanceLimits()
	referenceStatus, referenceOutput, referenceErr := reference.Operation(t.Context(), name, args, limits.MaxInput, limits.MaxOutput)
	var fault *rt.FaultError
	if errors.As(err, &fault) {
		if referenceErr == nil {
			t.Fatalf("translated trap without reference trap: %v", err)
		}
		return status, nil
	}
	if referenceErr == nil {
		referenceErr = rt.FromStatus(name, referenceStatus, referenceOutput)
	}
	if (err == nil) != (referenceErr == nil) {
		t.Fatalf("%s error mismatch: Go=%v reference=%v", name, err, referenceErr)
	}
	if err != nil {
		if err.Error() != referenceErr.Error() {
			t.Fatalf("%s errors differ: Go=%v reference=%v", name, err, referenceErr)
		}
		return status, nil
	}
	if status != referenceStatus || !bytes.Equal(output, referenceOutput) {
		t.Fatalf("%s differs: Go=(%d,%x) reference=(%d,%x)", name, status, output, referenceStatus, referenceOutput)
	}
	return status, output
}
func (g *guest) instanceLimits() rt.Limits {
	return rt.Limits{MaxInput: generatedInputLimit, MaxOutput: generatedOutputLimit, MaxMemory: maximumMemory}
}
func generatedSeed[T any](t testing.TB, encode func(T, uint64) ([]byte, error), value T) []byte {
	t.Helper()
	data, err := encode(value, generatedInputLimit)
	if err != nil {
		t.Fatal(err)
	}
	return data
}
func TestGeneratedDifferential(t *testing.T) {
	t.Parallel()
	for _, test := range generatedCases(t) {
		t.Run(test.name, func(t *testing.T) {
			g, reference := newDifferential(t)
			compareOperation(t, g, reference, test.name, test.args)
		})
	}
}
func FuzzGeneratedDifferential(f *testing.F) {
	f.Add(uint8(0), uint64(0), []byte{})
	f.Add(uint8(0), uint64(1), []byte{255, 0, 1})
	f.Fuzz(func(t *testing.T, selector uint8, scalar uint64, data []byte) {
		if len(data) > 4096 {
			t.Skip()
		}
		cases := generatedCases(t)
		if len(cases) == 0 {
			t.Skip()
		}
		test := cases[int(selector)%len(cases)]
		bufferSet, scalarSet := false, false
		for index := range test.args {
			arg := &test.args[index]
			if arg.Buffer && !bufferSet {
				arg.Bytes = data
				bufferSet = true
			} else if !arg.Buffer && !scalarSet {
				arg.Value = scalar
				scalarSet = true
			}
		}
		g, reference := newDifferential(t)
		compareOperation(t, g, reference, test.name, test.args)
	})
}

const generatedInputLimit uint64 = 65536
const generatedOutputLimit uint64 = 65536

func generatedInvoke(g *guest, name string, args []cocoontest.Arg, pointers []uint32) rt.Status {
	switch name {
	case "cocoon_echo":
		return rt.Status(g.module.Xcocoon_echo(int32(pointers[0]), int32(len(args[0].Bytes))))
	case "cocoon_join":
		return rt.Status(g.module.Xcocoon_join(int32(pointers[0]), int32(len(args[0].Bytes)), int32(pointers[1]), int32(len(args[1].Bytes))))
	case "cocoon_bounce":
		return rt.Status(g.module.Xcocoon_bounce(int32(pointers[0]), int32(len(args[0].Bytes))))
	case "cocoon_scalar_values":
		return rt.Status(g.module.Xcocoon_scalar_values(int32(args[0].Value), int32(args[1].Value), int64(args[2].Value), int64(args[3].Value), math.Float32frombits(uint32(args[4].Value)), math.Float64frombits(args[5].Value), int32(args[6].Value)))
	case "cocoon_test_trap":
		return rt.Status(g.module.Xcocoon_test_trap(int32(args[0].Value)))
	case "cocoon_counter_new":
		return rt.Status(g.module.Xcocoon_counter_new(int64(args[0].Value)))
	case "cocoon_counter_add":
		return rt.Status(g.module.Xcocoon_counter_add(int64(args[0].Value), int64(args[1].Value)))
	case "cocoon_counter_count":
		return rt.Status(g.module.Xcocoon_counter_count(int64(args[0].Value)))
	case "cocoon_counter_close":
		return rt.Status(g.module.Xcocoon_counter_close(int64(args[0].Value)))
	default:
		panic("unknown generated operation")
	}
}
func generatedCases(t testing.TB) []generatedCase {
	t.Helper()
	return []generatedCase{
		{name: "cocoon_echo", args: []cocoontest.Arg{{Buffer: true, Bytes: generatedSeed(t, encodeString, "")}}},
		{name: "cocoon_join", args: []cocoontest.Arg{{Buffer: true, Bytes: generatedSeed(t, encodeString, "")}, {Buffer: true, Bytes: generatedSeed(t, encodeString, "")}}},
		{name: "cocoon_bounce", args: []cocoontest.Arg{{Buffer: true, Bytes: generatedSeed(t, encodePayload, Payload{})}}},
		{name: "cocoon_scalar_values", args: []cocoontest.Arg{{}, {}, {}, {}, {}, {}, {}}},
		{name: "cocoon_test_trap", args: []cocoontest.Arg{{}}},
		{name: "cocoon_counter_new", args: []cocoontest.Arg{{}}},
		{name: "cocoon_counter_add", args: []cocoontest.Arg{{}, {}}},
		{name: "cocoon_counter_count", args: []cocoontest.Arg{{}}},
		{name: "cocoon_counter_close", args: []cocoontest.Arg{{}}},
	}
}

var _ = math.Float64bits
