package cli_test

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
)

// TestMain lets a copy of the test executable stand in for each external tool.
// The CLI itself still runs in the test process, so its errors are instrumented
// without requiring a Rust installation, a shell, or network access.
func TestMain(m *testing.M) {
	program := strings.TrimSuffix(filepath.Base(os.Args[0]), ".exe")
	if os.Getenv("COCOON_CLI_TEST_PROJECT") != "" && slices.Contains([]string{"rustup", "go", "wasm-opt", "wasm-metadce", "wasm-as"}, program) {
		output, err := fixtureTool(program, os.Args[1:])
		if err == nil {
			_, err = os.Stdout.Write(output)
		}
		if err != nil {
			if _, writeErr := fmt.Fprintln(os.Stderr, err); writeErr != nil {
				os.Exit(2)
			}
			os.Exit(1)
		}
		os.Exit(0)
	}
	os.Exit(m.Run())
}

func fixtureTool(program string, args []string) ([]byte, error) {
	project := os.Getenv("COCOON_CLI_TEST_PROJECT")
	failure := os.Getenv("COCOON_CLI_TEST_FAILURE")
	if failure != "" && (program == failure || slices.Contains(args, failure)) {
		return nil, fmt.Errorf("fixture failure: %s", failure)
	}
	switch program {
	case "rustup":
		if slices.Contains(args, "rustfmt") {
			return io.ReadAll(os.Stdin)
		}
		if slices.Contains(args, "component") {
			return []byte("rust-src\nrust-std-wasm32-unknown-unknown\n"), nil
		}
		if slices.Contains(args, "rustc") {
			if slices.Contains(args, "--print") {
				return []byte(project + "\n"), nil
			}
			return []byte("rustc 1.97.0 (fixture)\n"), nil
		}
		if slices.Contains(args, "metadata") {
			return json.Marshal(map[string]any{"packages": []any{map[string]any{"dependencies": []any{map[string]string{"name": "cocoon-guest", "path": filepath.Join(project, "guest")}}}}})
		}
		if slices.Contains(args, "generate-lockfile") {
			return nil, os.WriteFile("Cargo.lock", []byte("locked fixture"), 0o600)
		}
		if slices.Contains(args, "build") {
			return nil, nil
		}
	case "go":
		if slices.Contains(args, "-version") {
			return []byte("wasm2go v0.4.16\n"), nil
		}
		index := slices.Index(args, "-o")
		if index >= 0 && index+1 < len(args) {
			return nil, os.WriteFile(args[index+1], []byte("// Code generated by wasm2go. DO NOT EDIT.\npackage wasm\n"), 0o600) // #nosec G304 G703 -- The parent CLI supplies a destination in this test's temporary project.
		}
	case "wasm-opt", "wasm-metadce", "wasm-as":
		if slices.Contains(args, "--version") {
			return []byte(program + " version 133\n"), nil
		}
		index := slices.Index(args, "-o")
		if index >= 0 && index+1 < len(args) {
			data, err := os.ReadFile(filepath.Join(project, "fixture.wasm")) // #nosec G304 G703 -- Read only the test's copied ABI fixture.
			if err != nil {
				return nil, err
			}
			return nil, os.WriteFile(args[index+1], data, 0o600) // #nosec G304 G703 -- The parent CLI supplies a destination below a temporary directory.
		}
	}
	return nil, fmt.Errorf("unexpected fixture invocation: %s %v", program, args)
}

func cliProject(t *testing.T) (directory, manifestPath string) {
	t.Helper()
	directory = t.TempDir()
	for path, data := range map[string]string{
		"go.mod":           "module example.com/author\ngo 1.26\n",
		"shim/Cargo.lock":  "locked fixture",
		"shim/src/lib.rs":  "// authored fixture\n",
		"guest/Cargo.toml": "[package]\nname=\"cocoon-guest\"\n",
	} {
		writeCLIFile(t, filepath.Join(directory, path), []byte(data))
	}
	for source, target := range map[string]string{
		"../../testdata/compute/cocoon.toml":                     "cocoon.toml",
		"../../testdata/compute/go/compute/testdata/module.wasm": "fixture.wasm",
	} {
		data, err := os.ReadFile(source) // #nosec G304 -- Copy fixed checked-in fixtures into the temporary project.
		if err != nil {
			t.Fatal(err)
		}
		writeCLIFile(t, filepath.Join(directory, target), data)
	}
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	tools := t.TempDir()
	for _, program := range []string{"rustup", "go", "wasm-opt", "wasm-metadce", "wasm-as"} {
		if runtime.GOOS == "windows" {
			program += ".exe"
		}
		path := filepath.Join(tools, program)
		if linkErr := os.Link(executable, path); linkErr != nil {
			data, readErr := os.ReadFile(executable) // #nosec G304 -- Copy this test executable when hard links cross filesystem boundaries.
			if readErr != nil {
				t.Fatal(readErr)
			}
			if writeErr := os.WriteFile(path, data, 0o700); writeErr != nil { // #nosec G306 G703 -- Copy an executable into this test's private fixture directory.
				t.Fatal(writeErr)
			}
		}
	}
	t.Setenv("COCOON_CLI_TEST_PROJECT", directory)
	t.Setenv("COCOON_CLI_TEST_FAILURE", "")
	t.Setenv("COCOON_RUSTC_WRAPPER", "")
	t.Setenv("PATH", tools)
	t.Setenv("CARGO_HOME", filepath.Join(directory, "cargo-cache"))
	return directory, filepath.Join(directory, "cocoon.toml")
}

func writeCLIFile(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil { // #nosec G304 G703 -- Write the explicitly selected fixture below t.TempDir.
		t.Fatal(err)
	}
}

type failedOutput struct{}

func (failedOutput) Write([]byte) (int, error) { return 0, io.ErrClosedPipe }

func assertNoCLIFile(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("unexpected output %s: %v", path, err)
	}
}
