// Code generated by cocoon. DO NOT EDIT.
#![allow(unused_imports)]
use cocoon_guest::{Error, Result, Slab};
use std::cell::RefCell;
#[derive(Debug, Clone, PartialEq)]
pub struct Numbers {
    pub signed32: i32,
    pub unsigned32: u32,
    pub signed64: i64,
    pub unsigned64: u64,
    pub float32: f32,
    pub float64: f64,
    pub enabled: bool,
}
impl Numbers {
    pub fn decode(data: &[u8]) -> Result<Self> {
        let fields = cocoon_guest::decode_record(data, 7, 65536)?;
        Ok(Self {
            signed32: i32::from_le_bytes(
                fields[0]
                    .try_into()
                    .map_err(|_| Error::argument("scalar length"))?,
            ),
            unsigned32: u32::from_le_bytes(
                fields[1]
                    .try_into()
                    .map_err(|_| Error::argument("scalar length"))?,
            ),
            signed64: i64::from_le_bytes(
                fields[2]
                    .try_into()
                    .map_err(|_| Error::argument("scalar length"))?,
            ),
            unsigned64: u64::from_le_bytes(
                fields[3]
                    .try_into()
                    .map_err(|_| Error::argument("scalar length"))?,
            ),
            float32: f32::from_le_bytes(
                fields[4]
                    .try_into()
                    .map_err(|_| Error::argument("scalar length"))?,
            ),
            float64: f64::from_le_bytes(
                fields[5]
                    .try_into()
                    .map_err(|_| Error::argument("scalar length"))?,
            ),
            enabled: match fields[6] {
                [0] => false,
                [1] => true,
                _ => return Err(Error::argument("invalid bool")),
            },
        })
    }
    pub fn encode(self) -> Result<Vec<u8>> {
        cocoon_guest::encode_record(
            &[
                self.signed32.to_le_bytes().to_vec(),
                self.unsigned32.to_le_bytes().to_vec(),
                self.signed64.to_le_bytes().to_vec(),
                self.unsigned64.to_le_bytes().to_vec(),
                self.float32.to_le_bytes().to_vec(),
                self.float64.to_le_bytes().to_vec(),
                vec![u8::from(self.enabled)],
            ],
            65536,
        )
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct Payload {
    pub label: String,
    pub data: Vec<u8>,
    pub numbers: Numbers,
    pub signed32: Vec<i32>,
    pub unsigned32: Vec<u32>,
    pub signed64: Vec<i64>,
    pub unsigned64: Vec<u64>,
    pub float32: Vec<f32>,
    pub float64: Vec<f64>,
}
impl Payload {
    pub fn decode(data: &[u8]) -> Result<Self> {
        let fields = cocoon_guest::decode_record(data, 9, 65536)?;
        Ok(Self {
            label: String::from_utf8(fields[0].to_vec())
                .map_err(|_| Error::argument("invalid UTF-8"))?,
            data: fields[1].to_vec(),
            numbers: Numbers::decode(fields[2])?,
            signed32: {
                if !fields[3].len().is_multiple_of(4) {
                    return Err(Error::argument("slice length"));
                }
                fields[3]
                    .chunks_exact(4)
                    .map(|__chunk| {
                        Ok(i32::from_le_bytes(
                            __chunk
                                .try_into()
                                .map_err(|_| Error::argument("scalar length"))?,
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?
            },
            unsigned32: {
                if !fields[4].len().is_multiple_of(4) {
                    return Err(Error::argument("slice length"));
                }
                fields[4]
                    .chunks_exact(4)
                    .map(|__chunk| {
                        Ok(u32::from_le_bytes(
                            __chunk
                                .try_into()
                                .map_err(|_| Error::argument("scalar length"))?,
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?
            },
            signed64: {
                if !fields[5].len().is_multiple_of(8) {
                    return Err(Error::argument("slice length"));
                }
                fields[5]
                    .chunks_exact(8)
                    .map(|__chunk| {
                        Ok(i64::from_le_bytes(
                            __chunk
                                .try_into()
                                .map_err(|_| Error::argument("scalar length"))?,
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?
            },
            unsigned64: {
                if !fields[6].len().is_multiple_of(8) {
                    return Err(Error::argument("slice length"));
                }
                fields[6]
                    .chunks_exact(8)
                    .map(|__chunk| {
                        Ok(u64::from_le_bytes(
                            __chunk
                                .try_into()
                                .map_err(|_| Error::argument("scalar length"))?,
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?
            },
            float32: {
                if !fields[7].len().is_multiple_of(4) {
                    return Err(Error::argument("slice length"));
                }
                fields[7]
                    .chunks_exact(4)
                    .map(|__chunk| {
                        Ok(f32::from_le_bytes(
                            __chunk
                                .try_into()
                                .map_err(|_| Error::argument("scalar length"))?,
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?
            },
            float64: {
                if !fields[8].len().is_multiple_of(8) {
                    return Err(Error::argument("slice length"));
                }
                fields[8]
                    .chunks_exact(8)
                    .map(|__chunk| {
                        Ok(f64::from_le_bytes(
                            __chunk
                                .try_into()
                                .map_err(|_| Error::argument("scalar length"))?,
                        ))
                    })
                    .collect::<Result<Vec<_>>>()?
            },
        })
    }
    pub fn encode(self) -> Result<Vec<u8>> {
        cocoon_guest::encode_record(
            &[
                self.label.into_bytes(),
                self.data,
                self.numbers.encode()?,
                self.signed32
                    .iter()
                    .flat_map(|__value| __value.to_le_bytes())
                    .collect::<Vec<u8>>(),
                self.unsigned32
                    .iter()
                    .flat_map(|__value| __value.to_le_bytes())
                    .collect::<Vec<u8>>(),
                self.signed64
                    .iter()
                    .flat_map(|__value| __value.to_le_bytes())
                    .collect::<Vec<u8>>(),
                self.unsigned64
                    .iter()
                    .flat_map(|__value| __value.to_le_bytes())
                    .collect::<Vec<u8>>(),
                self.float32
                    .iter()
                    .flat_map(|__value| __value.to_le_bytes())
                    .collect::<Vec<u8>>(),
                self.float64
                    .iter()
                    .flat_map(|__value| __value.to_le_bytes())
                    .collect::<Vec<u8>>(),
            ],
            65536,
        )
    }
}
#[allow(clippy::upper_case_acronyms)]
pub trait API {
    type Counter;
    fn echo(&mut self, arg0: String) -> Result<String>;
    fn join(&mut self, arg0: String, arg1: String) -> String;
    fn bounce(&mut self, arg0: Payload) -> Payload;
    #[allow(clippy::too_many_arguments)]
    fn scalar_values(
        &mut self,
        arg0: i32,
        arg1: u32,
        arg2: i64,
        arg3: u64,
        arg4: f32,
        arg5: f64,
        arg6: bool,
    ) -> Numbers;
    fn test_trap(&mut self, arg0: u32);
    fn counter_new(&mut self, arg0: u64) -> Self::Counter;
    fn counter_add(&mut self, resource: &mut Self::Counter, arg0: u64) -> Result<u64>;
    fn counter_count(&mut self, resource: &mut Self::Counter) -> u64;
    fn counter_close(&mut self, resource: Self::Counter) {
        drop(resource);
    }
}
struct State {
    service: crate::Shim,
    counter: Slab<<crate::Shim as API>::Counter>,
}
thread_local! { static STATE: RefCell<State> = RefCell::new(State { service: Default::default(),
counter: Slab::default(),
}); }
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_abi_version() -> u32 {
    cocoon_guest::ABI_VERSION
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_schema_hash() -> u64 {
    4076813288107292652u64
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_init() {
    cocoon_guest::init(65536, 65536)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_in_reserve(length: usize) -> *mut u8 {
    cocoon_guest::reserve(length)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_out() -> *const cocoon_guest::Output {
    cocoon_guest::output()
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_trim(keep: usize) {
    cocoon_guest::trim(keep)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_alloc(length: usize) -> *mut u8 {
    cocoon_guest::alloc(length)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_echo(arg0_ptr: usize, arg0_len: usize) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __arg0 = cocoon_guest::input(arg0_ptr, arg0_len)?;
        let arg0 = String::from_utf8(__arg0).map_err(|_| Error::argument("invalid UTF-8"))?;
        let __value = __state.service.echo(arg0)?;
        Ok(__value.into_bytes())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_join(
    arg0_ptr: usize,
    arg0_len: usize,
    arg1_ptr: usize,
    arg1_len: usize,
) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __arg0 = cocoon_guest::input(arg0_ptr, arg0_len)?;
        let arg0 = String::from_utf8(__arg0).map_err(|_| Error::argument("invalid UTF-8"))?;
        let __arg1 = cocoon_guest::input(arg1_ptr, arg1_len)?;
        let arg1 = String::from_utf8(__arg1).map_err(|_| Error::argument("invalid UTF-8"))?;
        let __value = __state.service.join(arg0, arg1);
        Ok(__value.into_bytes())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_bounce(arg0_ptr: usize, arg0_len: usize) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __arg0 = cocoon_guest::input(arg0_ptr, arg0_len)?;
        let arg0 = Payload::decode(__arg0.as_slice())?;
        let __value = __state.service.bounce(arg0);
        __value.encode()
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_scalar_values(
    arg0: i32,
    arg1: u32,
    arg2: i64,
    arg3: u64,
    arg4: f32,
    arg5: f64,
    arg6: u32,
) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let arg6 = match arg6 {
            0 => false,
            1 => true,
            _ => return Err(Error::argument("invalid bool")),
        };
        let __value = __state
            .service
            .scalar_values(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
        __value.encode()
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_test_trap(arg0: u32) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<()> {
        __state.service.test_trap(arg0);
        Ok(())
    });
    cocoon_guest::reply_unit(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_counter_new(arg0: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __value = __state.service.counter_new(arg0);
        let __handle = __state.counter.insert(__value)?;
        Ok(__handle.to_le_bytes().to_vec())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_counter_add(__handle: u64, arg0: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __resource = __state.counter.get_mut(__handle)?;
        let __value = __state.service.counter_add(__resource, arg0)?;
        Ok(__value.to_le_bytes().to_vec())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_counter_count(__handle: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __resource = __state.counter.get_mut(__handle)?;
        let __value = __state.service.counter_count(__resource);
        Ok(__value.to_le_bytes().to_vec())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_counter_close(__handle: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<()> {
        let __resource = __state.counter.remove(__handle)?;
        __state.service.counter_close(__resource);
        Ok(())
    });
    cocoon_guest::reply_unit(__result)
}
