// Code generated by cocoon. DO NOT EDIT.
#![allow(unused_imports)]
use cocoon_guest::{Error, Result, Slab};
use std::cell::RefCell;
#[allow(clippy::upper_case_acronyms)]
pub trait API {
    type Sketch;
    fn obfuscate_sql(&mut self, arg0: String) -> Result<String>;
    fn obfuscate_traces(&mut self, arg0: Vec<u8>) -> Result<Vec<u8>>;
    fn sketch_new(&mut self) -> Self::Sketch;
    fn sketch_add(&mut self, resource: &mut Self::Sketch, arg0: f64) -> Result<()>;
    fn sketch_add_many(&mut self, resource: &mut Self::Sketch, arg0: Vec<f64>) -> Result<()>;
    fn sketch_count(&mut self, resource: &mut Self::Sketch) -> f64;
    fn sketch_encode(&mut self, resource: &mut Self::Sketch) -> Vec<u8>;
    fn sketch_close(&mut self, resource: Self::Sketch) {
        drop(resource);
    }
}
struct State {
    service: crate::Shim,
    sketch: Slab<<crate::Shim as API>::Sketch>,
}
thread_local! { static STATE: RefCell<State> = RefCell::new(State { service: Default::default(),
sketch: Slab::default(),
}); }
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_abi_version() -> u32 {
    cocoon_guest::ABI_VERSION
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_schema_hash() -> u64 {
    10905104844739090753u64
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_init() {
    cocoon_guest::init(67108864, 67108864)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_in_reserve(length: usize) -> *mut u8 {
    cocoon_guest::reserve(length)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_out() -> *const cocoon_guest::Output {
    cocoon_guest::output()
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_trim(keep: usize) {
    cocoon_guest::trim(keep)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_alloc(length: usize) -> *mut u8 {
    cocoon_guest::alloc(length)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_obfuscate_sql(arg0_ptr: usize, arg0_len: usize) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __arg0 = cocoon_guest::input(arg0_ptr, arg0_len)?;
        let arg0 = String::from_utf8(__arg0).map_err(|_| Error::argument("invalid UTF-8"))?;
        let __value = __state.service.obfuscate_sql(arg0)?;
        Ok(__value.into_bytes())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_obfuscate_traces(arg0_ptr: usize, arg0_len: usize) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __arg0 = cocoon_guest::input(arg0_ptr, arg0_len)?;
        let arg0 = __arg0;
        let __value = __state.service.obfuscate_traces(arg0)?;
        Ok(__value)
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_sketch_new() -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __value = __state.service.sketch_new();
        let __handle = __state.sketch.insert(__value)?;
        Ok(__handle.to_le_bytes().to_vec())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_sketch_add(__handle: u64, arg0: f64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __resource = __state.sketch.get_mut(__handle)?;
        __state.service.sketch_add(__resource, arg0)?;
        Ok(Vec::new())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_sketch_add_many(__handle: u64, arg0_ptr: usize, arg0_len: usize) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __arg0 = cocoon_guest::input(arg0_ptr, arg0_len)?;
        let arg0 = {
            if !__arg0.as_slice().len().is_multiple_of(8) {
                return Err(Error::argument("slice length"));
            }
            __arg0
                .as_slice()
                .chunks_exact(8)
                .map(|__chunk| {
                    Ok(f64::from_le_bytes(
                        __chunk
                            .try_into()
                            .map_err(|_| Error::argument("scalar length"))?,
                    ))
                })
                .collect::<Result<Vec<_>>>()?
        };
        let __resource = __state.sketch.get_mut(__handle)?;
        __state.service.sketch_add_many(__resource, arg0)?;
        Ok(Vec::new())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_sketch_count(__handle: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __resource = __state.sketch.get_mut(__handle)?;
        let __value = __state.service.sketch_count(__resource);
        Ok(__value.to_le_bytes().to_vec())
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_sketch_encode(__handle: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __resource = __state.sketch.get_mut(__handle)?;
        let __value = __state.service.sketch_encode(__resource);
        Ok(__value)
    });
    cocoon_guest::reply(__result)
}
#[unsafe(no_mangle)]
pub extern "C" fn cocoon_sketch_close(__handle: u64) -> i32 {
    let __result = STATE.with_borrow_mut(|__state| -> Result<Vec<u8>> {
        let __resource = __state.sketch.remove(__handle)?;
        __state.service.sketch_close(__resource);
        Ok(Vec::new())
    });
    cocoon_guest::reply(__result)
}
