// Code generated by wasm2go. DO NOT EDIT.

package trapfix

import (
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int64
}

func New() *Module {
	m := new(Module)
	m.t0 = make([]any, 3)
	m.maxMem = 3
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{fn0, fn1}}
	table_init(m.t0, m.elements[0], i32(0), 0, len(m.elements[0]))
	m.elements[0] = nil
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func fn0() int32 {
	return i32(1)
}
func fn1(v0 int32) int32 {
	return v0
}
func (m *Module) Xunreachable() {
	panic("unreachable")
}
func (m *Module) Xload_oob() {
	_ = int32(load32(m.memory, uint32(i32(-1))))
}
func (m *Module) Xdiv_zero() int32 {
	t0 := i32(1) / i32(0)
	return t0
}
func (m *Module) Xi32_overflow() int32 {
	t0 := i32_neg_s(i32(-0x80000000))
	return t0
}
func (m *Module) Xi64_overflow() int64 {
	t0 := i64_neg_s(i64(-0x8000000000000000))
	return t0
}
func (m *Module) Xbad_conversion() int32 {
	t0 := i32_trunc_f64_s(math.Float64frombits(0x7ff8000000000000))
	return t0
}
func (m *Module) Xindirect_null() int32 {
	t0 := m.t0[cocoon_table_index(uint64(uint(i32(2))), len(m.t0))].(func() int32)()
	return t0
}
func (m *Module) Xindirect_mismatch() int32 {
	t0 := m.t0[cocoon_table_index(uint64(uint(i32(1))), len(m.t0))].(func() int32)()
	return t0
}
func (m *Module) Xtable_oob() int32 {
	t0 := m.t0[cocoon_table_index(uint64(uint(i32(3))), len(m.t0))].(func() int32)()
	return t0
}
func (m *Module) Xtable_get_oob() {
	_ = m.t0[cocoon_table_index(uint64(i32(-1)), len(m.t0))]
}
func (m *Module) Xfill(v0, v1, v2 int32) {
	memory_fill(m.memory, uint32(v0), v1, uint32(v2))
}
func (m *Module) Xzero(v0, v1 int32) {
	memory_zero(m.memory, uint32(v0), uint32(v1))
}
func (m *Module) Xcopy(v0, v1, v2 int32) {
	memory_copy(m.memory, uint32(v0), uint32(v1), uint32(v2))
}
func (m *Module) Xinit(v0, v1, v2 int32) {
	memory_init(m.memory, data0, uint32(v0), uint32(v1), uint32(v2))
}
func (m *Module) Xgrow(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, int64(v0), m.maxMem))
	return t0
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(mem[addr:])
	}
	_ = mem[uint64(addr)+3]
	val := *(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr)))
	if big {
		return bits.ReverseBytes32(val)
	}
	return val
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i32_neg_s(x int32) int32 {
	if x == math.MinInt32 {
		panic("integer overflow")
	}
	return -x
}

//go:nosplit
func i64_neg_s(x int64) int64 {
	if x == math.MinInt64 {
		panic("integer overflow")
	}
	return -x
}

//go:nosplit
func i32_trunc_f64_s(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	}
	return int32(x)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	*mem = append(buf, make([]byte, int(new<<16)-len)...)
	return int64(old)
}

func memory_init[T1, T2 int | uint32 | uint64](mem []byte, data string, dest T1, src, n T2) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y:len(mem)], data[z:w])
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y:len(mem)], mem[z:w:len(mem)])
}

func memory_fill[T uint32 | uint64](mem []byte, dest T, val int32, n T) {
	x := uint64(dest)
	y := x + uint64(n)
	buf := mem[x:y:len(mem)]
	if len(buf) > 0 {
		buf[0] = byte(val)
		for i := 1; i < len(buf); {
			chunk := min(i, 8192)
			i += copy(buf[i:], buf[:chunk])
		}
	}
}

func memory_zero[T uint32 | uint64](mem []byte, dest, n T) {
	x := uint64(dest)
	y := x + uint64(n)
	clear(mem[x:y:len(mem)])
}

func table_init[T1, T2, T3 int | int32 | int64](tab, elems []any, dest T1, src T2, n T3) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(cocoon_table_slice(tab, uint64(x), uint64(y)), cocoon_table_slice(elems, uint64(z), uint64(w)))
}

const data0 = "abc"

func cocoon_table_index(index uint64, length int) int {
	if index >= uint64(
		length) {
		panic("out of bounds table access")
	}
	return int(index)
}
func cocoon_table_slice(table []any, low, high uint64) []any {
	if low >
		high || high > uint64(len(table)) {
		panic("out of bounds table access")
	}
	return table[low:high:len(table)]
}
