(module
  (type $returns_i32 (func (result i32)))
  (memory (export "memory") 1 3)
  (table 3 funcref)
  (func $correct (result i32) (i32.const 1))
  (func $wrong (param i32) (result i32) (local.get 0))
  (elem (i32.const 0) $correct $wrong)
  (data $payload "abc")
  (func (export "unreachable") unreachable)
  (func (export "load_oob") (drop (i32.load (i32.const -1))))
  (func (export "div_zero") (result i32)
    (i32.div_s (i32.const 1) (i32.const 0)))
  (func (export "i32_overflow") (result i32)
    (i32.div_s (i32.const -2147483648) (i32.const -1)))
  (func (export "i64_overflow") (result i64)
    (i64.div_s (i64.const -9223372036854775808) (i64.const -1)))
  (func (export "bad_conversion") (result i32)
    (i32.trunc_f64_s (f64.const nan)))
  (func (export "indirect_null") (result i32)
    (call_indirect (type $returns_i32) (i32.const 2)))
  (func (export "indirect_mismatch") (result i32)
    (call_indirect (type $returns_i32) (i32.const 1)))
  (func (export "table_oob") (result i32)
    (call_indirect (type $returns_i32) (i32.const 3)))
  (func (export "table_get_oob") (drop (table.get (i32.const -1))))
  (func (export "fill") (param i32 i32 i32)
    (memory.fill (local.get 0) (local.get 1) (local.get 2)))
  (func (export "zero") (param i32 i32)
    (memory.fill (local.get 0) (i32.const 0) (local.get 1)))
  (func (export "copy") (param i32 i32 i32)
    (memory.copy (local.get 0) (local.get 1) (local.get 2)))
  (func (export "init") (param i32 i32 i32)
    (memory.init $payload (local.get 0) (local.get 1) (local.get 2)))
  (func (export "grow") (param i32) (result i32)
    (memory.grow (local.get 0)))
)
